apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment

  labels:

    app: nginx

spec: #deployment specifications

  replicas: 3

  selector:

    matchLabels:

      app: nginx

  template:

    metadata:

      labels:

        app: nginx

    spec:  #pod/container specifications

      containers:

      - name: nginx

        image: nginx:1.14.2

        ports:

        - containerPort: 80


